### ISSUE TITLE
Get media description out of bounds error

### ISSUE THREAD

**Issue by PembaTamang** [philipplackner/SpotifyCloneYT#3]
I am getting an error when clicking the songs.

   ```
 java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.spotifyclone.exoplayer.MusicService$MusicQueueNavigator.getMediaDescription(MusicService.kt:128)
```
this is the code that the error points to

```
    private inner class MusicQueueNavigator : TimelineQueueNavigator(mediaSession){
        override fun getMediaDescription(player: Player, windowIndex: Int): MediaDescriptionCompat {
          return firebaseMusicSource.songs[windowIndex].description
        }
```
the firebase music source class is identical to yours and I haven't missed any of the metadata that needs to be added. what could be the problem.

**Comment by PembaTamang** [comment]
firebaseMusicSource.songs is always zero and fetchMediaData inside FirebaseMusic source is not called at the onCreate of the MusicService class what could be the problem
